k9s:
  # General K9s styles
  body:
    fgColor: "#abb2bf"
    bgColor: default # Matches your transparent Waybar vibe
    logoColor: "#d19a66"

  # ClusterInfoView (Top left info)
  info:
    fgColor: "#d19a66"
    sectionColor: "#3e4452"

  frame:
    border:
      fgColor: "#5c6370"
      focusColor: "#d19a66" # Active window border

    menu:
      fgColor: "#abb2bf"
      keyColor: "#d19a66" # Hotkeys match your clock/active workspace
      numKeyColor: "#d19a66"

    crumbs:
      fgColor: "#282c34"
      bgColor: "#abb2bf"
      activeColor: "#d19a66"

    status:
      newColor: "#abb2bf"
      modifyColor: "#d19a66"
      addColor: "#abb2bf"
      errorColor: "#e06c75" # Matches your 'urgent'/'critical' color
      highlightcolor: "#d19a66"
      killColor: "#e06c75"
      completedColor: "#5c6370"

    title:
      fgColor: "#d19a66"
      bgColor: default
      highlightColor: "#3e4452"
      counterColor: "#abb2bf"
      filterColor: "#d19a66"

  views:
    table:
      fgColor: "#abb2bf"
      bgColor: default
      cursorColor: "#3e4452" # Subtle dark highlight for selection
      header:
        fgColor: "#d19a66"
        bgColor: default
        sorterColor: "#d19a66"

    yaml:
      keyColor: "#d19a66"
      colonColor: "#abb2bf"
      valueColor: "#3e4452"

    logs:
      fgColor: "#abb2bf"
      bgColor: default
      indicator:
        fgColor: "#d19a66"
