k9s:
  # General K9s styles
  body:
    fgColor: "#a89984"
    bgColor: default # Matches your transparent Waybar vibe
    logoColor: "#d79921"

  # ClusterInfoView (Top left info)
  info:
    fgColor: "#d79921"
    sectionColor: "#3c3836"

  frame:
    border:
      fgColor: "#7c6f64"
      focusColor: "#d79921" # Active window border

    menu:
      fgColor: "#a89984"
      keyColor: "#d79921" # Hotkeys match your clock/active workspace
      numKeyColor: "#d79921"

    crumbs:
      fgColor: "#000000"
      bgColor: "#a89984"
      activeColor: "#d79921"

    status:
      newColor: "#a89984"
      modifyColor: "#d79921"
      addColor: "#a89984"
      errorColor: "#cc241d" # Matches your 'urgent'/'critical' color
      highlightcolor: "#d79921"
      killColor: "#cc241d"
      completedColor: "#7c6f64"

    title:
      fgColor: "#d79921"
      bgColor: default
      highlightColor: "#3c3836"
      counterColor: "#a89984"
      filterColor: "#d79921"

  views:
    table:
      fgColor: "#a89984"
      bgColor: default
      cursorColor: "#3c3836" # Subtle dark highlight for selection
      header:
        fgColor: "#d79921"
        bgColor: default
        sorterColor: "#d79921"

    yaml:
      keyColor: "#d79921"
      colonColor: "#a89984"
      valueColor: "#3c3836"

    logs:
      fgColor: "#a89984"
      bgColor: default
      indicator:
        fgColor: "#d79921"
