k9s:
  # General K9s styles (Ayu Dark)
  body:
    fgColor: "#bfbdb6"
    bgColor: default
    logoColor: "#e6b450"

  # ClusterInfoView (Top left info)
  info:
    fgColor: "#e6b450"
    sectionColor: "#131721"

  frame:
    border:
      fgColor: "#565b66"
      focusColor: "#e6b450"

    menu:
      fgColor: "#bfbdb6"
      keyColor: "#39bae6"
      numKeyColor: "#e6b450"

    crumbs:
      fgColor: "#0b0e14"
      bgColor: "#565b66"
      activeColor: "#e6b450"

    status:
      newColor: "#bfbdb6"
      modifyColor: "#39bae6"
      addColor: "#aad94c"
      errorColor: "#d95757"
      highlightcolor: "#e6b450"
      killColor: "#d95757"
      completedColor: "#565b66"

    title:
      fgColor: "#e6b450"
      bgColor: default
      highlightColor: "#131721"
      counterColor: "#bfbdb6"
      filterColor: "#d2a6ff"

  views:
    table:
      fgColor: "#bfbdb6"
      bgColor: default
      cursorColor: "#131721"
      header:
        fgColor: "#e6b450"
        bgColor: default
        sorterColor: "#d2a6ff"

    yaml:
      keyColor: "#e6b450"
      colonColor: "#bfbdb6"
      valueColor: "#565b66"

    logs:
      fgColor: "#bfbdb6"
      bgColor: default
      indicator:
        fgColor: "#39bae6"
