#!/usr/bin/env sh

# Global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_zoom_persist          on
yabai -m config window_shadow                on
yabai -m config window_animation_duration    0.0
yabai -m config window_animation_frame_rate  120
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_opacity               off
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config window_border_width          4
yabai -m config window_border_radius         12
yabai -m config window_border_blur           off
yabai -m config window_border_hidpi          on
yabai -m config window_border                off
yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 on
yabai -m config top_padding                  45
yabai -m config bottom_padding               12
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   04
yabai -m config layout                       bsp
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# Rules for apps
yabai -m rule --add app="^Ghostty$" manage=on
yabai -m rule --add app="^Google Chrome$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off

echo "yabai configuration loaded.."