# btop Ayu Dark theme (https://github.com/ayu-theme/ayu-colors)

theme[main_bg]="#0b0e14"
theme[main_fg]="#bfbdb6"
theme[title]="#e6b450"
theme[hi_fg]="#ff8f40"
theme[selected_bg]="#131721"
theme[selected_fg]="#bfbdb6"
theme[inactive_fg]="#565b66"
theme[graph_text]="#565b66"
theme[proc_misc]="#aad94c"

theme[cpu_box]="#e6b450"
theme[mem_box]="#39bae6"
theme[net_box]="#d2a6ff"
theme[proc_box]="#e6b450"
theme[div_line]="#131721"

theme[temp_start]="#39bae6"
theme[temp_mid]="#e6b450"
theme[temp_end]="#d95757"

theme[cpu_start]="#aad94c"
theme[cpu_mid]="#ffb454"
theme[cpu_end]="#ff8f40"

theme[free_start]="#aad94c"
theme[free_mid]=""
theme[free_end]="#39bae6"

theme[cached_start]="#59c2ff"
theme[cached_mid]=""
theme[cached_end]="#d2a6ff"

theme[available_start]="#bfbdb6"
theme[available_mid]=""
theme[available_end]="#aad94c"

theme[used_start]="#e6b450"
theme[used_mid]="#ff8f40"
theme[used_end]="#d95757"

theme[download_start]="#131721"
theme[download_mid]="#39bae6"
theme[download_end]="#59c2ff"

theme[upload_start]="#131721"
theme[upload_mid]="#d2a6ff"
theme[upload_end]="#f07178"
