# btop Oxocarbon theme (https://github.com/nyoom-engineering/oxocarbon)

theme[main_bg]="#161616"
theme[main_fg]="#dde1e6"
theme[title]="#be95ff"
theme[hi_fg]="#ee5396"
theme[selected_bg]="#393939"
theme[selected_fg]="#dde1e6"
theme[inactive_fg]="#525252"
theme[graph_text]="#525252"
theme[proc_misc]="#42be65"

theme[cpu_box]="#be95ff"
theme[mem_box]="#33b1ff"
theme[net_box]="#ee5396"
theme[proc_box]="#be95ff"
theme[div_line]="#262626"

theme[temp_start]="#33b1ff"
theme[temp_mid]="#be95ff"
theme[temp_end]="#fa4d56"

theme[cpu_start]="#42be65"
theme[cpu_mid]="#33b1ff"
theme[cpu_end]="#ee5396"

theme[free_start]="#42be65"
theme[free_mid]=""
theme[free_end]="#33b1ff"

theme[cached_start]="#82cfff"
theme[cached_mid]=""
theme[cached_end]="#be95ff"

theme[available_start]="#dde1e6"
theme[available_mid]=""
theme[available_end]="#42be65"

theme[used_start]="#be95ff"
theme[used_mid]="#ee5396"
theme[used_end]="#fa4d56"

theme[download_start]="#262626"
theme[download_mid]="#33b1ff"
theme[download_end]="#82cfff"

theme[upload_start]="#262626"
theme[upload_mid]="#be95ff"
theme[upload_end]="#ee5396"
