# Set default shell
set-option -g default-shell /bin/bash

# Set prefix to Ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Enable mouse support
set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

# Enable TPM Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

# Reload Tmux configuration and install TPM plugins
bind r source-file ~/.tmux.conf \; display "Reloaded!"
run-shell ~/.tmux/plugins/tpm/tpm 

# isntall plugins 
bind I run-shell '~/.tmux/plugins/tpm/bin/install_plugins'
bind U run-shell '~/.tmux/plugins/tpm/bin/update_plugins all'


# Split panes
bind | split-window -h
bind - split-window -v

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Window navigation
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10

# Colors (Matte Black)
set -g status-style bg="#121212",fg="#eaeaea"
set -g status-left "#[fg=#f59e0b,bg=#121212] #S "
set -g status-right "#[fg=#f59e0b,bg=#121212]  #(basename #{pane_current_path}) | #H | #(uptime | awk '{print $3}' | sed 's/,//') hrs"
setw -g window-status-style fg=#f59e0b,bg=#121212
setw -g window-status-current-style fg=#121212,bg=#f59e0b
setw -g window-status-format " #W:#I "
setw -g window-status-current-format " #W:#I "

set -g pane-border-style fg=#333333
set -g pane-active-border-style fg=#f59e0b

set -g message-style bg=#f59e0b,fg=#121212

