# Background
background {
    path = ~/Pictures/wallpapers/better2.jpeg
    blur_passes = 3
    blur_size = 8
    contrast = 1.0
    brightness = 0.9
    vibrancy = 0.5
}

# User prompt
input-field {
    size = 500, 100
    outline_thickness = 7
    outline_color = rgb(FFFFFF)
    font_family = JetBrainsMono Nerd Font
    font_size = 28
    inner_color = rgba(64,62,65,0.0)
    outer_color = rgba(0,0,0,0)
    text_color = rgb(FFFFFF)
    font_color = rgb(FFFFFF)
    fade_on_empty = false
    dot_size = 1
    dot_color = rgb(FFFFFF)
    rounding = 0
    position = 0, 60
    valign = center
    halign = center
    placeholder_text = locked 
}

# Fail feedback (shake + red outline)
auth_fail {
    outer_color = rgb(b91c1c)      # Matte Black red
    fail_text = "incorrect"
}

