format = """
$username$hostname$directory$git_branch$git_status$git_state$python$cmd_duration$character
"""
add_newline = false

[directory]
style = "bold #7aa2f7"
 truncation_length = 3
truncate_to_repo = true
format = "[$path]($style) "

[character]
success_symbol = "[∷](bold #7aa2f7)"
error_symbol = "[∷](bold #f7768e)"
vimcmd_symbol = "[∷](bold #7dcfff)"

[git_branch]
symbol = " "                        # branch symbol
format = "[$symbol$branch]($style) "
style = "bold #7aa2f7"

[git_status]
format = "([$all_status$ahead_behind]($style)) "
style = "#7aa2f7"
conflicted = "="
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
stashed = "≡"

[git_state]
format = "[$state( $progress_current/$progress_total)]($style)"
style = "bold #ff9e64"

[cmd_duration]
min_time = 500
format = " [$duration]($style) "
style = "#565f89"

[python]
symbol = "  "                          # Python logo glyph
format = "[$symbol$virtualenv]($style)"
style = "#7dcfff"

[username]
style_user = "bold #7aa2f7"
style_root = "bold #ff9e64"
format = "[$user]($style)@"
disabled = false
show_always = true

[hostname]
ssh_only = true
format = "📡 [$hostname]($style) "
style = "bold #7dcfff"
disabled = false
