return {
	notify_on_error = true,
	format_on_save = true,
	formatters_by_ft = {
		lua = { "stylua" },
		python = { "black" },
		javascript = { "prettier" },
		typescript = { "prettier" },
		go = { "gofmt" },
		rust = { "rustfmt" },
		zig = { "zigfmt" },
		c = { "clang_format" },
		cpp = { "clang_format" },
		csharp = { "csharpier" },
		json = { "prettier" },
		toml = { "taplo" },
		yaml = { "prettier" },
		markdown = { "prettier" },
		html = { "prettier" },
		css = { "prettier" },
		sh = { "shfmt" },
		typst = { "prettytypst" },
		groovy = { "groovyformatter" },
	},
}