gui:
  theme:
    activeBorderColor:
      - "#d79921"
      - bold
    inactiveBorderColor:
      - "#7c6f64"
    optionsTextColor:
      - "#d79921"
    selectedLineBgColor:
      - "#3c3836"
    cherryPickedCommitBgColor:
      - "#d79921"
    cherryPickedCommitFgColor:
      - "#000000"
    unstagedChangesColor:
      - "#cc241d"
    defaultFgColor:
      - "#a89984"
    searchingActiveBorderColor:
      - "#d79921"
