gui:
  theme:
    activeBorderColor:
      - "#a7c080"
      - bold
    inactiveBorderColor:
      - "#424b50"
    optionsTextColor:
      - "#a7c080"
    selectedLineBgColor:
      - "#424b50"
    selectedRangeBgColor:
      - "#424b50"
    cherryPickedCommitBgColor:
      - "#a7c080"
    cherryPickedCommitFgColor:
      - "#2d353b"
    unstagedChangesColor:
      - "#e67e80"
    defaultFgColor:
      - "#d3c6aa"
    searchingActiveBorderColor:
      - "#a7c080"
    searchingMatchFgColor:
      - "#2d353b"
    searchingMatchBgColor:
      - "#a7c080"
    diffTerminalColor:
      - "#d3c6aa"
    diffAddedFgColor:
      - "#a7c080"
    diffAddedBgColor:
      - "#2d353b"
    diffModifiedFgColor:
      - "#859289"
    diffModifiedBgColor:
      - "#2d353b"
    diffDeletedFgColor:
      - "#e67e80"
    diffDeletedBgColor:
      - "#2d353b"
    diffUntrackedFgColor:
      - "#859289"
    diffUntrackedBgColor:
      - "#2d353b"
    diffStagedAddedFgColor:
      - "#a7c080"
    diffStagedAddedBgColor:
      - "#2d353b"
    diffStagedModifiedFgColor:
      - "#859289"
    diffStagedModifiedBgColor:
      - "#2d353b"
    diffStagedDeletedFgColor:
      - "#e67e80"
    diffStagedDeletedBgColor:
      - "#2d353b"
    diffStagedUntrackedFgColor:
      - "#859289"
    diffStagedUntrackedBgColor:
      - "#2d353b"
    mergeConflictBgColor:
      - "#e67e80"
    mergeConflictFgColor:
      - "#2d353b"
    commitHashColor:
      - "#859289"
    commitTimeColor:
      - "#859289"
    commitAuthorColor:
      - "#a7c080"
    commitMessageColor:
      - "#d3c6aa"
    branchFgColor:
      - "#a7c080"
    branchCurrentFgColor:
      - "#a7c080"
    branchCurrentBgColor:
      - "#2d353b"
    tagFgColor:
      - "#a7c080"
    remoteBranchFgColor:
      - "#859289"
    pullRequestFgColor:
      - "#859289"
    statusShortBranchFgColor:
      - "#a7c080"
    statusShortBranchBgColor:
      - "#2d353b"
    statusShortStatusFgColor:
      - "#d3c6aa"
    statusShortStatusBgColor:
      - "#2d353b"
    fileStagedFgColor:
      - "#a7c080"
    fileUnstagedFgColor:
      - "#859289"
    fileUntrackedFgColor:
      - "#859289"
    fileDeletedFgColor:
      - "#e67e80"
    fileAddedFgColor:
      - "#a7c080"
    fileModifiedFgColor:
      - "#859289"
    fileRenamedFgColor:
      - "#859289"
    fileCopiedFgColor:
      - "#859289"
    fileIgnoredFgColor:
      - "#859289"