gui:
  theme:
    activeBorderColor:
      - "#e6b450"
      - bold
    inactiveBorderColor:
      - "#565b66"
    optionsTextColor:
      - "#39bae6"
    selectedLineBgColor:
      - "#131721"
    cherryPickedCommitBgColor:
      - "#e6b450"
    cherryPickedCommitFgColor:
      - "#0b0e14"
    unstagedChangesColor:
      - "#d95757"
    defaultFgColor:
      - "#bfbdb6"
    searchingActiveBorderColor:
      - "#d2a6ff"
git:
  overrideGpg: true
  pagers:
    - pager: critique --stdin
