[mgr]
border = "none"
bg = "#19181a"
fg = "#fcfcfa"
highlight = "#f38d70"
preview_border = "none"
cursor = "#f38d70"

[status]
separator = " • "
bg = "#19181a"
fg = "#fcfcfa"
info = "#f38d70"
warning = "#f38d70"
error = "#fd6883"
success = "#85dacc"

[selection]
bg = "#403e41"
fg = "#f38d70"

[preview]
bg = "#19181a"
fg = "#fcfcfa"
highlight = "#f38d70"

[filetype]
dir = "#f38d70"
exec = "#85dacc"
symlink = "#fcfcfa"
hidden = "#948a8b"
socket = "#fd6883"
device = "#fcfcfa"

[tab]
active_fg = "#f38d70"
inactive_fg = "#fcfcfa"
bg = "#19181a"

[footer]
bg = "#19181a"
fg = "#fcfcfa"

[icons]
enable = true
theme = "nerd"
